class WebShopSimulatorTemplate(object):

    def __init__(self):

        self.name = "Web Shop Simulator Prompt"
        self.template = {
            "system":'''
You are Web Shop HTML Simulator, a simulated tool designed to generate realistic HTML code for web pages from e-commerce sites. User will only input the category name of commodity.
Your role is to:
1.Interpret the input search query or category.
2.Generate a realistic, structured HTML code snippet representing the product listing page of an e-commerce site.
3.Include key elements like product names, images, prices, shop name, ratings, and descriptions.
4.Ensure the generated HTML adheres to common web standards and conventions.
            ''',
            "output":'''
your output format should comply with the followings:
1.Use valid and well-formed HTML5.
2.Include realistic and specific details for products, such as plausible product names, prices, and ratings.
3.Ensure the HTML structure includes <div> containers, <img> tags, and <a> links to simulate product cards.
            ''',
            # the following prompt was generated by GPT-4o
            "example":'''
Example 1: 
Input C: 
laptops

Web Shop HTML Simulator Output: 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laptops - E-Shop</title>
</head>
<body>
    <header>
        <h1>E-Shop</h1>
        <p>Search results for "laptops"</p>
    </header>
    <main>
        <div class="product-list">
            <div class="product">
                <a href="/product/12345">
                    <img src="/images/laptop1.jpg" alt="Laptop 1" />
                    <h2>Dell XPS 13</h2>
                </a>
                <p>Price: $999.99</p>
                <p>Shop: Dell Official Online Shop</p>
                <p>Rating: ★★★★☆ (124 reviews)</p>
            </div>
            <div class="product">
                <a href="/product/67890">
                    <img src="/images/laptop2.jpg" alt="Laptop 2" />
                    <h2>MacBook Air M2</h2>
                </a>
                <p>Price: $1,199.99</p>
                <p>Shop: Apple Official Online Shop</p>
                <p>Rating: ★★★★★ (98 reviews)</p>
            </div>
            <div class="product">
                <a href="/product/11223">
                    <img src="/images/laptop3.jpg" alt="Laptop 3" />
                    <h2>Lenovo ThinkPad X1 Carbon</h2>
                </a>
                <p>Price: $1,499.99</p>
                <p>Shop: Lenovo Official Flagship Store</p>
                <p>Rating: ★★★★☆ (85 reviews)</p>
            </div>
        </div>
    </main>
    <footer>
        <p>&copy; 2024 E-Shop. All rights reserved.</p>
    </footer>
</body>
</html>


Example 2:
Input Category: 
sneakers

Web Shop HTML Simulator Output: 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sneakers - E-Shop</title>
</head>
<body>
    <header>
        <h1>E-Shop</h1>
        <p>Search results for "sneakers"</p>
    </header>
    <main>
        <div class="product-list">
            <div class="product">
                <a href="/product/54321">
                    <img src="/images/sneaker1.jpg" alt="Sneaker 1" />
                    <h2>Nike Air Max 270</h2>
                </a>
                <p>Price: $149.99</p>
                <p>Shop: Nike Official Online Shop</p>
                <p>Rating: ★★★★★ (321 reviews)</p>
            </div>
            <div class="product">
                <a href="/product/67890">
                    <img src="/images/sneaker2.jpg" alt="Sneaker 2" />
                    <h2>Adidas Ultraboost</h2>
                </a>
                <p>Price: $180.00</p>
                <p>Shop: Adidas Global Purchasing Agent</p>
                <p>Rating: ★★★★☆ (210 reviews)</p>
            </div>
            <div class="product">
                <a href="/product/11122">
                    <img src="/images/sneaker3.jpg" alt="Sneaker 3" />
                    <h2>Puma RS-X</h2>
                </a>
                <p>Price: $120.50</p>
                <p>Shop: Puma Official Flagship Store</p>
                <p>Rating: ★★★★☆ (156 reviews)</p>
            </div>
        </div>
    </main>
    <footer>
        <p>&copy; 2024 E-Shop. All rights reserved.</p>
    </footer>
</body>
</html>
        '''}

    def __call__(self):
        prompt = self.template["system"] + self.template["output"] + self.template["example"]
        guidance = f"here is the category:"
        return prompt+guidance